# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [64]:
import numpy as np
np.__version__

'1.26.4'

2) Создать нулевой вектор размера 10

In [65]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [66]:
np.repeat(7,7)

array([7, 7, 7, 7, 7, 7, 7])

5) Создать вектор заполненный четными числами от 10 до 100

In [67]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [68]:
np.random.randint(0, 100, 10)[::-1]

array([14, 53, 23, 26, 82, 96, 64, 92, 44, 52])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [69]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [70]:
matrix = np.zeros((4, 4))
np.fill_diagonal(matrix[1:], 1)
matrix = matrix.transpose()

matrix

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [71]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, [1, 2, 3, 4])

matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [72]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [73]:
matrix = np.random.randint(0, 10, (10, 10))

matrix

array([[9, 8, 5, 4, 2, 7, 5, 1, 1, 8],
       [7, 4, 6, 8, 4, 2, 8, 2, 6, 1],
       [7, 3, 6, 2, 2, 0, 8, 9, 8, 6],
       [3, 9, 2, 2, 8, 4, 1, 1, 4, 3],
       [8, 5, 8, 2, 6, 5, 6, 1, 9, 0],
       [7, 6, 3, 1, 2, 4, 0, 6, 1, 0],
       [7, 2, 9, 5, 1, 9, 0, 1, 7, 9],
       [1, 5, 3, 7, 3, 6, 8, 7, 5, 2],
       [2, 6, 4, 4, 0, 2, 5, 3, 4, 4],
       [8, 5, 3, 0, 7, 7, 8, 1, 3, 0]])

In [74]:
mean_rows = matrix.mean(axis=1, keepdims=True)

mean_rows

array([[5. ],
       [4.8],
       [5.1],
       [3.7],
       [5. ],
       [3. ],
       [5. ],
       [4.7],
       [3.4],
       [4.2]])

In [75]:
matrix - mean_rows

array([[ 4. ,  3. ,  0. , -1. , -3. ,  2. ,  0. , -4. , -4. ,  3. ],
       [ 2.2, -0.8,  1.2,  3.2, -0.8, -2.8,  3.2, -2.8,  1.2, -3.8],
       [ 1.9, -2.1,  0.9, -3.1, -3.1, -5.1,  2.9,  3.9,  2.9,  0.9],
       [-0.7,  5.3, -1.7, -1.7,  4.3,  0.3, -2.7, -2.7,  0.3, -0.7],
       [ 3. ,  0. ,  3. , -3. ,  1. ,  0. ,  1. , -4. ,  4. , -5. ],
       [ 4. ,  3. ,  0. , -2. , -1. ,  1. , -3. ,  3. , -2. , -3. ],
       [ 2. , -3. ,  4. ,  0. , -4. ,  4. , -5. , -4. ,  2. ,  4. ],
       [-3.7,  0.3, -1.7,  2.3, -1.7,  1.3,  3.3,  2.3,  0.3, -2.7],
       [-1.4,  2.6,  0.6,  0.6, -3.4, -1.4,  1.6, -0.4,  0.6,  0.6],
       [ 3.8,  0.8, -1.2, -4.2,  2.8,  2.8,  3.8, -3.2, -1.2, -4.2]])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [76]:
matrix = np.random.randint(0, 10, (10, 10))

matrix

array([[4, 4, 3, 7, 6, 5, 0, 0, 1, 0],
       [1, 0, 6, 2, 9, 4, 9, 3, 0, 8],
       [0, 3, 8, 7, 9, 8, 7, 7, 0, 8],
       [3, 8, 3, 8, 6, 1, 8, 4, 6, 9],
       [3, 1, 5, 6, 1, 1, 5, 9, 9, 6],
       [0, 5, 3, 7, 9, 6, 2, 8, 9, 6],
       [1, 9, 8, 1, 6, 6, 1, 0, 2, 8],
       [7, 4, 9, 1, 9, 1, 7, 3, 5, 4],
       [0, 3, 1, 7, 6, 1, 6, 1, 2, 3],
       [8, 4, 3, 6, 3, 3, 7, 7, 9, 1]])

In [77]:
median_cols = np.median(matrix, axis=0, keepdims=True)

median_cols

array([[2. , 4. , 4. , 6.5, 6. , 3.5, 6.5, 3.5, 3.5, 6. ]])

In [78]:
matrix - median_cols

array([[ 2. ,  0. , -1. ,  0.5,  0. ,  1.5, -6.5, -3.5, -2.5, -6. ],
       [-1. , -4. ,  2. , -4.5,  3. ,  0.5,  2.5, -0.5, -3.5,  2. ],
       [-2. , -1. ,  4. ,  0.5,  3. ,  4.5,  0.5,  3.5, -3.5,  2. ],
       [ 1. ,  4. , -1. ,  1.5,  0. , -2.5,  1.5,  0.5,  2.5,  3. ],
       [ 1. , -3. ,  1. , -0.5, -5. , -2.5, -1.5,  5.5,  5.5,  0. ],
       [-2. ,  1. , -1. ,  0.5,  3. ,  2.5, -4.5,  4.5,  5.5,  0. ],
       [-1. ,  5. ,  4. , -5.5,  0. ,  2.5, -5.5, -3.5, -1.5,  2. ],
       [ 5. ,  0. ,  5. , -5.5,  3. , -2.5,  0.5, -0.5,  1.5, -2. ],
       [-2. , -1. , -3. ,  0.5,  0. , -2.5, -0.5, -2.5, -1.5, -3. ],
       [ 6. ,  0. , -1. , -0.5, -3. , -0.5,  0.5,  3.5,  5.5, -5. ]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [79]:
matrix = np.random.randint(0, 5, (5, 5))

matrix

array([[2, 3, 4, 2, 2],
       [3, 2, 2, 1, 1],
       [2, 4, 0, 4, 2],
       [3, 2, 0, 4, 1],
       [4, 0, 4, 0, 1]])

In [80]:
np.hstack([matrix, matrix.min(axis=1).reshape(-1, 1), matrix.max(axis=1).reshape(-1, 1)])

array([[2, 3, 4, 2, 2, 2, 4],
       [3, 2, 2, 1, 1, 1, 3],
       [2, 4, 0, 4, 2, 0, 4],
       [3, 2, 0, 4, 1, 0, 4],
       [4, 0, 4, 0, 1, 0, 4]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [81]:
vector = np.arange(1, 51)
odd_mat = vector[vector % 2 != 0].reshape(5, 5)
even_mat = vector[vector % 2 == 0].reshape(5, 5)

odd_mat, even_mat

(array([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19],
        [21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39],
        [41, 43, 45, 47, 49]]),
 array([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40],
        [42, 44, 46, 48, 50]]))

In [82]:
odd_mat @ even_mat

array([[ 750,  800,  850,  900,  950],
       [1850, 2000, 2150, 2300, 2450],
       [2950, 3200, 3450, 3700, 3950],
       [4050, 4400, 4750, 5100, 5450],
       [5150, 5600, 6050, 6500, 6950]])

In [83]:
np.linalg.inv(odd_mat @ even_mat)

LinAlgError: Singular matrix

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [84]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])